#
# Dockerfile for zenoss/zenoss-centos-base.<VERSION>.devtools - the base image for Zenoss development images.
#
FROM zenoss/zenoss-centos-base:%VERSION%

ENV JAVA_HOME=/usr/lib/jvm/jre \
    GOROOT=/go \
    GOPATH=/gosrc \
    PATH=$PATH:/opt/maven/bin:/go/bin

RUN sed -i 's/requiretty/!requiretty/' /etc/sudoers

RUN yum install epel-release -y \
	&& yum makecache \
    && yum groups install -y 'Development Tools' \
	&& yum install -y --setopt=tsflags="nodocs" \
		bc \
		bzip2-devel \
		bzr \
		cyrus-sasl-devel \
		gdbm-devel \
		java-11-openjdk-devel \
		mercurial \
		mock \
		pango-devel \
		perl-XML-XPath \
		protobuf-compiler \
		python-devel \
		python-virtualenv \
		readline-devel \
		sqlite-devel \
    && yum erase epel-release -y \
	&& yum autoremove -y \
	&& yum clean all \
    && /sbin/scrub.sh

#
# Install Maven
#
RUN mkdir -p /opt/maven
RUN wget -qO- http://apache.osuosl.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz | tar -C /opt/maven -xz --strip-components=1

#
# Install golang
#
RUN wget -qO- https://storage.googleapis.com/golang/go1.14.6.linux-amd64.tar.gz | tar -C / -xz
