FROM zenoss/centos-base:1.0.2-java
MAINTAINER Zenoss <dev@zenoss.com>

# Add application users/groups
RUN groupadd        -g 1201         -r epmd && \
    useradd -u 1201 -g epmd         -r epmd         -d /tmp -s /sbin/nologin -c "Erlang Port Mapper Daemon" && \
    groupadd        -g 1202         -r nagios && \
    useradd -u 1202 -g nagios       -r nagios       -d /var/spool/nagios -s /sbin/nologin && \
    groupadd        -g 1203         -r rabbitmq && \
    useradd -u 1203 -g rabbitmq     -r rabbitmq     -d /var/lib/rabbitmq -c "RabbitMQ messaging server" && \
    groupadd        -g 1204         -r redis && \
    useradd -u 1204 -g redis        -r redis        -d /var/lib/redis -s /sbin/nologin -c "Redis Database Server" && \
    groupadd        -g 1205         -r memcached && \
    useradd -u 1205 -g memcached    -r memcached    -d /run/memcached -s /sbin/nologin -c "Memcached daemon" && \
    groupadd        -g 1207         -r solr && \
    useradd -u 1207 -g solr         -r solr         -d /opt/solr -s /sbin/nologin -c "Solr" && \
    groupadd        -g 1206         -r zenoss


# TODO: change this repo to use zenoss yum repo
RUN yum install epel-release -y && \
    yum install -y \
        device-mapper-libs \
        libaio \
        libgomp \
        openssl-devel \
        pcre-devel \
        protobuf-python \
        libart_lgpl \
        libasyncns \
        xorg-x11-fonts-Type1 \
        /tmp/%RPM% && \
    yum erase epel-release -y && \
    /sbin/scrub.sh

# Symlink /etc/localtime
RUN rm -f /etc/localtime && ln -s /usr/share/zoneinfo/UTC /etc/localtime

# Creating sym link to remedy library import of serviced
RUN ln -s /lib64/libdevmapper.so.1.02 /lib64/libdevmapper.so.1.02.1

# Install Solr
RUN mkdir -p /opt/solr && \
    wget -qO- http://archive.apache.org/dist/lucene/solr/5.5.0/solr-5.5.0.tgz | tar -C /opt/solr -xz --strip-components=1 && \
    mkdir -p /opt/solr/server/solr/lib && \
    chown -R solr:solr /opt/solr

ADD ./rpm/pkgroot/%RPM% /tmp/%RPM%
RUN yum install epel-release -y && \
    yum install -y \
        /tmp/%RPM% && \
    yum erase epel-release -y && \
    /sbin/scrub.sh

RUN echo -e "NODENAME=rabbit@rbt0\nNODE_IP_ADDRESS=0.0.0.0" > /etc/rabbitmq/rabbitmq-env.conf
ADD my.cnf /etc/my.cnf
