FROM zenoss/centos-base:%BASE_VERSION%
MAINTAINER Zenoss <dev@zenoss.com>

COPY my.cnf /etc/my.cnf
COPY rpm/dest/%RPM_DEPS% /tmp/
COPY %RPM_LIBSMI% /tmp/
COPY %PYDEPS% /tmp/
COPY %JSBUILDER% /tmp/
COPY %PHANTOMJS% /tmp/
COPY zenoss_env_init.sh  /tmp/zenoss_env_init.sh
COPY zenoss_deps_install.sh  /tmp/zenoss_deps_install.sh

RUN chmod +x /tmp/zenoss_env_init.sh /tmp/zenoss_deps_install.sh && /tmp/zenoss_env_init.sh
