FROM zenoss/centos-base:%BASE_VERSION%
MAINTAINER Zenoss <dev@zenoss.com>

ADD my.cnf /etc/my.cnf

ADD ./rpm/pkgroot/%RPM_DEPS% /tmp/%RPM_DEPS%
ADD ./%RPM_LIBSMI% /tmp/%RPM_LIBSMI%

ADD zenoss_env_init.sh  /tmp/zenoss_env_init.sh
ADD zenoss_deps_install.sh  /tmp/zenoss_deps_install.sh

RUN chmod +x /tmp/zenoss_env_init.sh /tmp/zenoss_deps_install.sh && /tmp/zenoss_env_init.sh
