#
# FPM Dockerfile
#
# https://github.com/dockerfile/fpm
#

# Pull base image.
FROM ruby
RUN gem install fpm
RUN apt-get update && apt-get install -y rpm && apt-get clean && rm -rf /var/lib/apt/lists/*

# Configure default user as the host user
RUN groupadd -f -g %GID% build
RUN useradd -d /home/build -m -s /bin/bash -u %UID% -g %GID% build
RUN echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
USER build
